### ISSUE TITLE
Memory reporting incorrect and OS on Linux.

### ISSUE THREAD

**Issue by Freejack01** [Akkadius/Occulus#16]
I noticed something odd in the admin panel, when running the server. I monitor the actual server and the admin panel and noticed teh admin panel reports memory usage at 3% more than the actual server reports being used. Also it reports Debian Buster as the OS when in reality it is Linux Mint 20.3. 

I have checked the processes in bashtop and htop just to be sure and they both report the same. So not sure where it is having the reporting off.

I think I see what it is doing, it appears to be reading actual mem usage then adding cache to it. That is the only thin g that could possibly be showing this total. So basically 5% mem usage and 3% cache usage.

**Comment by Akkadius** [comment]
Are you running it within a docker container? It's not going to report correctly there

**Comment by Freejack01** [comment]
Yeah it is now included in Akkadius/Stack for EQemu. Ishows both mem usage and cache usage as basically all the system memory.
