### ISSUE TITLE
Request: in-game countdown added to shutdown command like restart has

### ISSUE THREAD

**Issue by Isaaru** [Akkadius/Occulus#19]
Would be a nice feature to have the in-game "world is coming down in X minutes" system messages added to the "Stop Server" command similar to what Restart has.

**Comment by Akkadius** [comment]
Agreed

**Comment by Akkadius** [comment]
![image](https://user-images.githubusercontent.com/3319450/211264044-3ace3ffc-a4d8-4eba-aa2c-0a754448fc3f.png)

This will go in next release
